name: dsan5400-final-project
channels:
  - apple
  - conda-forge
dependencies:
  - datasets
  - more-itertools
  - nltk
  - numpy
  - pip
  - pytest
  - python
  - jupyter
  - tqdm
  - transformers
  - scikit-learn
  - pandas
  - collections
  - emoji
  - tkinter
  - argparse
  - os

